// IMPORTS -
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Navbar } from "@/components/navbar";
import { cn } from "@/lib/utils";
import Providers from "./providers";
import "./globals.css";

// PARTIALS -
const font = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "p-3 h-auto w-full space-y-4 bg-slate-200",
          font.className
        )}
      >
        <Navbar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
